Make buffer pos more visible in alternate modeline
NicolasPetton/zerodark-theme pull request #23
Opened 2016-11-04 09:25 UTC by DamienCassou

2016-11-04 10:38 UTC, NicolasPetton requested changes

2016-11-04 10:38 UTC, NicolasPetton commented on zerodark-theme.el
>    "Alternate mode line construct for displaying the position in the buffer.")
It has to look different in inactive-mode-line.

2016-11-04 10:38 UTC, NicolasPetton commented on zerodark-theme.el
> +  '((t :foreground "#cccccc" :height 0.9))
`#cccccc` is the same color as the active-mode-line, isn't it? If that's what you want, then we can just remove the face property.

If it's not what you want, you could choose a slightly darker grey to dim it a bit.

2016-11-04 10:39 UTC, NicolasPetton commented
@DamienCassou could you make future PRs here instead https://petton.fr/git/nico/zerodark-theme?

2016-11-05 19:36 UTC, DamienCassou commented
I opened a new one at: https://petton.fr/git/nico/zerodark-theme/pulls/2

2016-11-05 19:36 UTC, closed without merging